# Numpy 기초연습문제

---

In [1]:
import numpy as np   #numpy 불러오기

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3, 4))   #.zeros로 모든 원소가 0인 행렬 생성하기
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

```python
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
```

In [5]:
for i in range(a.shape[0]):     #a.shape[0]은 ndarray a의 행의 개수 = 3
    for j in range(a.shape[1]):    #a.shape[1]은 열의 개수 = 4
        a[i, j] = i*4 + j + 1     #i = 0부터 2까지, j = 0부터 3까지 반복
a

4


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [9]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num    #a의 행과 열에 차례대로 num 넣기
        num += 1   #num은 1씩 증가
a    #위와 같은 결과

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [10]:
a[1, 2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

```python
array([[5., 6., 7., 8.]])
```

In [11]:
a.shape   #2차원 ndarray

(3, 4)

In [12]:
a[[1], :]    #차원이 유지되도록 열에 ':'기호 기입

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

```python
array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])
```

In [13]:
a[:, [0,2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

```python
array([1., 2., 3., 4., 5., 6.])
```

In [17]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [18]:
a[a <= 6]  #위와 같은 결과

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [19]:
b = np.random.random((3, 4))
b

array([[0.41123876, 0.25055044, 0.21331734, 0.09378148],
       [0.93363428, 0.26619693, 0.76134955, 0.0374833 ],
       [0.15335235, 0.29751974, 0.96266688, 0.39187372]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [20]:
c = a * b
c

array([[ 0.41123876,  0.50110088,  0.63995203,  0.3751259 ],
       [ 4.66817139,  1.59718156,  5.32944688,  0.29986643],
       [ 1.38017116,  2.97519745, 10.58933572,  4.7024846 ]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [23]:
d = b.T
d

array([[0.41123876, 0.93363428, 0.15335235],
       [0.25055044, 0.26619693, 0.29751974],
       [0.21331734, 0.76134955, 0.96266688],
       [0.09378148, 0.0374833 , 0.39187372]])

In [24]:
d = np.transpose(b)  #위와 같은 결과
d

array([[0.41123876, 0.93363428, 0.15335235],
       [0.25055044, 0.26619693, 0.29751974],
       [0.21331734, 0.76134955, 0.96266688],
       [0.09378148, 0.0374833 , 0.39187372]])

In [25]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [26]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [27]:
e = a.dot(d)
e

array([[ 1.92741757,  3.90001001,  5.20388736],
       [ 5.80296966, 11.89466627, 12.42553814],
       [ 9.67852174, 19.88932252, 19.64718893]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [28]:
np.sum(e, axis=1)   #axis=1, 열을 기준으로 합을 계산하기

array([11.03131494, 30.12317407, 49.21503319])